import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { AiFillAlert, AiFillFacebook, AiFillGithub, AiFillLinkedin, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import devjordan from "../public/avatar1.png";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import popup from 'reactjs-popup';
import 'reactjs-popup/dist/index.css';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jordan Lee | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.ico" />
      </Head>
        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className= "min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="dark:text-gray-300 text-xl font-burtons">Jordan Lee</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"></BsFillMoonStarsFill></li>
                <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"  target="_blank" href="myresume.pdf" >Resume</a></li>
            </ul>
          </nav>
          <div className="text-center">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Jordan Lee</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300">Developer, Engineer, Scientist</h3>
            <p className="text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">Just a nice dude who likes to code and learn. It's pretty neat.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            
            <a href="https://github.com/jordanrlee" target="_blank"><AiFillGithub></AiFillGithub></a>
            <a href="https://www.linkedin.com/in/devjordanlee/" target="_blank"><AiFillLinkedin></AiFillLinkedin></a>
            
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500  rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            {/* image goes here*/}
            <Image src={devjordan} layout="fill" objectFit="cover"></Image>
          </div>
          </section>
          
          {/* second page */}
          <section className="min-h-screen">
            <div className="text-center p-10 ">
              <h3 className="text-3xl py-1 dark:text-teal-500">Just a bit about me</h3>
              <p className="text-medium py-2 leading-8 text-gray-800 dark:text-gray-300">Well, it all started when I was a kid. My Playstation 2 wouldn't function so I was upset. I couldn't afford to
               replace it, so I had to take matters into my own hands. I disassembled the console, learned the design of the hardware, and reassembled it.
              what I learned, was that I love <span className="text-teal-500">technology</span>, and if I keep pushing myself to learn, I can accomplish what I need to do. Pretty soon, I was fixing my friend's consoles and
               later it blossomed into building my own computers and learning to <span className="text-teal-500">code</span>.</p>
              <p className="text-medium py-2 leading-8 text-gray-800 dark:text-gray-300">Knowledge has been my pursuit in life. Being a single Dad, I needed to prove to my kids that education can expand
              the opportunites to seize <span className="text-teal-500">life-long memories</span>. I did this by obtaining my Bachelors of Science, majoring in <span className="text-teal-500">Computer Science</span>.
                </p>

              </div>
              {/* cards */}
              <div className="lg:flex gap-5">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-500">
                <div className="text-center"><Image src={code} width="100" height="100"></Image></div>
                <h3 className="text-2xl font-medium pt-8 pb-2 py-1">Person-Centered Coding</h3>
                {/* add an animation around end-user later */}
                <p>Finally, a dude that cares about the <span className="text-teal-500">end-user</span>. Modern design is not just about the look, but also the functionality and practicality of it's surrounding environment.
                The end product should visually be appealing and be so usable that even a caveman could use it (Give me a time machine, I'll prove it!).</p>
                <h4 className="text-lg py-1 leading-8 text-center">Tools of the Trade</h4>
                <ul className="flex justify-center gap-4">
                  <li className="text-gray-800 py-1">React</li>
                  <li className="text-gray-800 py-1">Tailwind</li>
                  <li className="text-gray-800 py-1">Next.js</li>
                  <li className="text-gray-800 py-1">Java</li>
                  <li className="text-gray-800 py-1">C#</li>
                  <li className="text-gray-800 py-1">MySQL</li>
                  <li className="text-gray-800 py-1">GitHub</li>
                </ul>
              
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-500">
                <div className=""><Image src={design} width="100" height="100"></Image></div>
                <h3 className="text-2xl font-medium pt-8 pb-2 py-1">The Pursuit of Knowledge</h3>
                {/* add an animation around end-user later */}
                <p>Being the <span className="text-teal-500">life-long learner</span> that I am, learning doesn't just stop at college.
                Although I have my bachelors degree, I am always looking for new ways to expand my knowledge. I am currently learning about Game Development
                using the <span className="text-teal-500">Phaser 3 Framework</span>. I also just so happen to be looking to start my Masters program in Computer Science in the near future.
                </p>
                <h4 className="text-lg py-1 leading-8 text-center">Bachelor's of Science, Computer Science</h4>
                <ul>
                  <li className="text-gray-800 py-1">Weber State University, Utah</li>
                  <li className="text-gray-800 py-1">Graduated 2023</li>
                </ul>
                
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-500">
                <div className=""><Image src={consulting} width="100" height="100"></Image></div>
                <h3 className="text-2xl font-medium pt-8 pb-2 py-1">Expert in Management and Communication</h3>
                {/* add an animation around end-user later */}
                <p>One of the benefits of working with me is that I have an extensive background in management. This translates
                  to effective communication and enable me to <span className="text-teal-500">get the job done</span>. I have worked with some of the most difficult situations
                  in the healthcare industry that have taught me to be an expert in critical thinking and rapid problem solving. This experience will serve me in the tech field 
                  as I work with my team. Because of these skills, I aim to achieve the position of CTO in the future.
                </p>
                <h4 className="text-lg py-1 leading-8 text-center">Skills</h4>
                <ul className="flex justify-center gap-4">
                  <li className="text-gray-800 py-1">Conflict Resolution and De-escalation</li>
                  <li className="text-gray-800 py-1">Teambuilding and Teamwork</li>
                  <li className="text-gray-800 py-1">Mentorship and Coaching</li>
                  <li className="text-gray-800 py-1">Constructive Critisism</li>
                  <li className="text-gray-800 py-1">Active Listening and Adaptability</li>
                </ul>
              </div>
            </div>
            </section>
            {/* third page */}
            <section className="min-h-screen">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-500">
                <h3 className="text-3xl dark:bg-slate-500 dark:text-teal-500">The Portfolio</h3>
                <p className=" dark:bg-slate-500">It looks like you made it to the end. I'd give you a high-five, but I don't want to break my monitor.
                  Instead, take a look at some of my work and know that I owe you a high-five.</p>
              </div>
              <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image src={web1} className="rounded-lg object-cover" width="100" height="100" layout="responsive"></Image>
                </div>
                <div className="basis-1/3 flex-1"> 
                <Image src={web2} className="rounded-lg object-cover" width="100" height="100" layout="responsive"></Image>
                </div >
                <div className="basis-1/3 flex-1"> 
                <Image src={web3} className="rounded-lg object-cover" width="100" height="100" layout="responsive"></Image>
                </div >
                <div className="basis-1/3 flex-1"> 
                <Image src={web4} className="rounded-lg object-cover" width="100" height="100" layout="responsive"></Image>
                </div >
              </div>

              </section>
          </main>
          <footer className="dark:bg-slate-500">
            <div className="flex justify-center gap-4">
              Jordan Lee | 2023
              </div>
          </footer>
    </div>
    
  );

}


